trigger:
- main

schedules:
- cron: "0 0 1 * *"
  displayName: Monthly schedule
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python train_log.py --data "C:/Fraud_Detection/creditcard.csv"
  displayName: 'Train model'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/mlruns'
    artifactName: 'mlruns'
  displayName: 'Publish MLflow artifacts'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'YOUR_AZURE_SUBSCRIPTION'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az ml model register -n LogisticRegressionModel --path $(Pipeline.Workspace)/mlruns --model-framework ScikitLearn --model-framework-version 0.24.1
  displayName: 'Register model in Azure ML'
